Persistance layer integration
WynkLimited/AnalyticQueueManager pull request #1
Opened 2022-08-10 08:07 UTC by mohitbhallaairtel

**Changelog:** 

Added Persistent support for events.

New Changes: 66,419 bytes
Old Changes : 55,408  byes
-----------
Size diff = 11 kb

2022-08-10 17:35 UTC, Nikhil-iOS requested changes

2022-08-10 17:35 UTC, Nikhil-iOS commented on AnalyticQueueManager/Classes/EventManager/DBHelper.swift
> +        let fileURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
Can we avoid using try!?

2022-08-10 17:35 UTC, Nikhil-iOS commented on AnalyticQueueManager/Classes/EventManager/Event.swift
> +public class Event {
@mohitbhallaairtel Let's discuss this with @nitinchadhawynk, I would like to understand your reason behind this. I am pretty sure, that using value types would have been a fundamental selection he made to avoid threading issues, which I was highlighting.

2022-08-11 06:08 UTC, mohitbhallaairtel commented on AnalyticQueueManager/Classes/EventManager/DBHelper.swift
> +        let fileURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
Added do catch

2022-08-11 06:08 UTC, mohitbhallaairtel commented on AnalyticQueueManager/Classes/EventManager/Event.swift
> +public class Event {
Used Struct again.

2022-08-11 14:14 UTC, merged